[theme]
base = "dark"
baseFontSize = 16

# General color setup
textColor = "#e2e8f0"
primaryColor = "#6690da"
backgroundColor = "#1d293d"
secondaryBackgroundColor = "#0f172b"
codeTextColor = "#6690da"

# Widgets
showWidgetBorder = true
borderColor = "#ffffff"